### ISSUE TITLE
Event plugins throw permissions error

### ISSUE THREAD

**Issue by JABirchall** [JABirchall/NimdaTS3#21]
Plugins that are triggered by an event trigger
```Plugin with config file {$configFile} has not been loaded because its permissions aren't set correctly.```

Event based plugins should be ignored by permissions

**Comment by Najsr** [comment]
Solved - [Commit](https://github.com/JABirchall/NimdaTS3/commit/0d6a8006f9105de0f9765281c533de559168ea19)
