### ISSUE TITLE
How to trigger a Plugin with a php call

### ISSUE THREAD

**Issue by Gicminos** [JABirchall/NimdaTS3#27]
What is the best way for trigger a Plugin with a php call from another file?

Thanks

**Comment by JABirchall** [comment]
It isn't possible to trigger plugins from outside the bot.
The only way is via a periodic timer, teamspeak event or a command.

If you tell me what it is you are trying to achieve I can help you to find the best way of doing it.

**Comment by JABirchall** [comment]
There has been no response in over 1 month. Closing issue
