### ISSUE TITLE
How Create a Timer with Database Clearly ?

### ISSUE THREAD

**Issue by HellBz** [JABirchall/NimdaTS3#31]
I Try something, i write a Plugn for Checking Twitch Status and Chane channelname etc.

But i Cannot bring a Database for Running.

i use the public function install() in my Timer and Create a AdvancedTimerContract

But How NimDa Create a Database automaticly,

i create Database one time in Trigggered Function onetime and it Works

[AdvancedTimerContract.txt](https://github.com/JABirchall/NimdaTS3/files/2263808/AdvancedTimerContract.txt)
[TwitchStatus.txt](https://github.com/JABirchall/NimdaTS3/files/2263809/TwitchStatus.txt)

**Comment by JABirchall** [comment]
Atm nimda doesnt have an AdvancedTimerContract with database abstraction. Only the normal TimerContract. 

So nimda does not know that AdvancedTimerContract exists to install new plugins. In the mean time you will need to create the table your self using something like [SQLiteBroswer](https://sqlitebrowser.org/) if you are using SQLite or a different editor if you use a diffrent database like MySQL.
