### ISSUE TITLE
Issue with Channel Notifications

### ISSUE THREAD

**Issue by Polarcraft** [JABirchall/NimdaTS3#6]
So whenever a user joins the channel the bot is supposed to message the user with who joined and what channel.
The bot actually sends this message:
<19:10:43> "CavemanBot": %s has joined channel %s

**Comment by JABirchall** [comment]
That plugin was removed a while ago and is no longer supported, It was only added for testing purposes.
Current support plugins are here: https://github.com/JABirchall/NimdaTS3/tree/master/plugins
